const eventsData = [

{
id:501,
genre:"Conference",
name:"AI Future Tech Conference",
date:"10 Jul 2026",
time:"10:00 AM",
location:"Hyderabad",
organizer:"AI Leaders Forum",
venue:"HICC Convention Centre",
ticketPrice:2500,
gst:18,
totalSeats:500,
seatsBooked:210,
availableSeats:290,
discount3Seats:"10%",
discount5PlusSeats:"18%",
description:"A premier gathering of AI researchers, developers, and industry leaders discussing future trends in artificial intelligence, machine learning innovations, and ethical technology adoption. The conference includes keynote sessions, panel discussions, networking opportunities, and live demonstrations of cutting-edge AI tools shaping the future."
},

{
id:502,
genre:"Comedy",
name:"Bassi Unfiltered Live",
date:"19 Apr 2026",
time:"7:00 PM",
location:"Jaipur",
performer:"Anubhav Singh Bassi",
venue:"Birla Auditorium",
ticketPrice:1800,
gst:18,
totalSeats:400,
seatsBooked:260,
availableSeats:140,
discount3Seats:"8%",
discount5PlusSeats:"15%",
description:"An evening of hilarious storytelling and relatable comedy by Anubhav Singh Bassi. Known for his witty observations and real-life experiences, this live show promises laughter, engaging audience interaction, and unforgettable stand-up moments for comedy lovers across the city."
},

{
id:503,
genre:"Music",
name:"Arijit Singh Soulful Night",
date:"12 Apr 2026",
time:"7:30 PM",
location:"Mumbai",
performer:"Arijit Singh",
venue:"Jio World Garden",
ticketPrice:4500,
gst:18,
totalSeats:800,
seatsBooked:650,
availableSeats:150,
discount3Seats:"10%",
discount5PlusSeats:"20%",
description:"Experience a magical night of soulful melodies with Arijit Singh performing his greatest hits and romantic classics. This grand concert blends emotional music, mesmerizing stage production, and an unforgettable atmosphere where fans can sing along to timeless Bollywood songs."
},

{
id:504,
genre:"Exhibition",
name:"Modern Art Expo India",
date:"18 Jun 2026",
time:"11:00 AM",
location:"Ahmedabad",
organizer:"Indian Art Foundation",
venue:"Gujarat Convention Centre",
ticketPrice:900,
gst:18,
totalSeats:350,
seatsBooked:140,
availableSeats:210,
discount3Seats:"7%",
discount5PlusSeats:"12%",
description:"Explore contemporary creativity at this modern art exhibition showcasing paintings, installations, sculptures, and digital artwork from emerging and established Indian artists. Visitors can interact with artists, attend guided tours, and discover innovative artistic expressions from across the country."
},

{
id:505,
genre:"Exhibition",
name:"AutoTech Showcase",
date:"21 Jun 2026",
time:"12:00 PM",
location:"Chennai",
organizer:"AutoTech India",
venue:"Chennai Trade Centre",
ticketPrice:1200,
gst:18,
totalSeats:500,
seatsBooked:220,
availableSeats:280,
discount3Seats:"10%",
discount5PlusSeats:"15%",
description:"An exciting automotive technology exhibition featuring next-generation vehicles, electric mobility innovations, and advanced automotive engineering solutions. Industry experts, automobile enthusiasts, and tech professionals gather to explore the future of mobility and smart transportation systems."
},

{
id:506,
genre:"Performance",
name:"Contemporary Collective",
date:"16 May 2026",
time:"7:00 PM",
location:"Mumbai",
performer:"Contemporary Dance Crew",
venue:"NCPA Experimental Theatre",
ticketPrice:1600,
gst:18,
totalSeats:300,
seatsBooked:120,
availableSeats:180,
discount3Seats:"8%",
discount5PlusSeats:"15%",
description:"A vibrant contemporary dance performance featuring a talented ensemble blending modern choreography, expressive storytelling, and powerful music. The show highlights artistic movement, creative stage design, and emotional narratives that connect deeply with audiences."
},

{
id:507,
genre:"Fest & Fairs",
name:"Delhi Street Festival",
date:"06 Jun 2026",
time:"5:00 PM",
location:"Delhi",
organizer:"Delhi Cultural Council",
venue:"Connaught Place Central Park",
ticketPrice:700,
gst:18,
totalSeats:600,
seatsBooked:320,
availableSeats:280,
discount3Seats:"6%",
discount5PlusSeats:"12%",
description:"Celebrate vibrant street culture with food stalls, music performances, art installations, and cultural showcases. This lively festival brings together local artisans, street performers, and food vendors creating an energetic atmosphere full of flavors, creativity, and entertainment."
},

{
id:508,
genre:"Conference",
name:"Digital Marketing MeetUP",
date:"15 Jul 2026",
time:"9:00 AM",
location:"Pune",
organizer:"Growth Marketers Association",
venue:"Pune International Convention Centre",
ticketPrice:2000,
gst:18,
totalSeats:400,
seatsBooked:170,
availableSeats:230,
discount3Seats:"10%",
discount5PlusSeats:"18%",
description:"A knowledge-packed meetup for marketers, entrepreneurs, and digital strategists exploring SEO trends, social media marketing, data analytics, and brand growth strategies. Industry experts share insights, case studies, and practical tips to boost digital presence and online engagement."
},

{
id:509,
genre:"NightLife",
name:"DJ Chetas Neon Party",
date:"28 Apr 2026",
time:"10:00 PM",
location:"Mumbai",
performer:"DJ Chetas",
venue:"Dragonfly Experience",
ticketPrice:2200,
gst:18,
totalSeats:350,
seatsBooked:240,
availableSeats:110,
discount3Seats:"10%",
discount5PlusSeats:"18%",
description:"Dance the night away at an electrifying neon party featuring Bollywood remixes and high-energy beats by DJ Chetas. The vibrant lighting, lively crowd, and powerful sound create an unforgettable nightlife experience filled with music and celebration."
},

{
id:510,
genre:"Expos",
name:"Education Abroad Expo",
date:"24 Jul 2026",
time:"12:30 PM",
location:"Patna",
organizer:"Global Education Network",
venue:"Patna Convention Hall",
ticketPrice:500,
gst:18,
totalSeats:450,
seatsBooked:160,
availableSeats:290,
discount3Seats:"5%",
discount5PlusSeats:"10%",
description:"Meet representatives from top global universities and explore opportunities for studying abroad. Students can attend counseling sessions, learn about scholarships, visa processes, and international career options while connecting with education experts."
},

{
id:511,
genre:"Sports",
name:"Celebrity Football Clash",
date:"10 May 2026",
time:"5:00 PM",
location:"Hyderabad",
organizer:"Young India Sports Group",
venue:"Gachibowli Stadium",
ticketPrice:1500,
gst:18,
totalSeats:600,
seatsBooked:340,
availableSeats:260,
discount3Seats:"8%",
discount5PlusSeats:"15%",
description:"An exciting celebrity football match featuring actors, influencers, and sports personalities competing for charity and entertainment. Fans can enjoy thrilling gameplay, live music performances, and interactive fan zones in a high-energy sports atmosphere."
},

{
id:512,
genre:"Fest & Fairs",
name:"Goa Cultural Carnival",
date:"02 Jun 2026",
time:"4:00 PM",
location:"Goa",
organizer:"Goa Tourism Board",
venue:"Panaji Beachfront Grounds",
ticketPrice:800,
gst:18,
totalSeats:700,
seatsBooked:310,
availableSeats:390,
discount3Seats:"6%",
discount5PlusSeats:"12%",
description:"A colorful carnival celebrating Goa's culture with music, traditional dance, food stalls, and beachside entertainment. Visitors can enjoy local art, vibrant parades, cultural performances, and authentic Goan cuisine in a festive coastal atmosphere."
},

{
id:513,
genre:"Expos",
name:"Handicraft & Artisan Expo",
date:"28 Jul 2026",
time:"11:30 AM",
location:"Surat",
organizer:"Indian Artisan Guild",
venue:"Surat International Exhibition Centre",
ticketPrice:600,
gst:18,
totalSeats:350,
seatsBooked:120,
availableSeats:230,
discount3Seats:"7%",
discount5PlusSeats:"12%",
description:"Discover handmade crafts, textiles, pottery, and artisan products created by talented craftsmen from across India. The expo offers workshops, live demonstrations, and opportunities to purchase unique handmade items directly from skilled artisans."
},

{
id:514,
genre:"Open Mic",
name:"Indie Artists Open Stage",
date:"06 Aug 2026",
time:"7:00 PM",
location:"Nagpur",
performer:"Indie Artists Community",
venue:"Nagpur Cultural Hall",
ticketPrice:400,
gst:18,
totalSeats:250,
seatsBooked:90,
availableSeats:160,
discount3Seats:"5%",
discount5PlusSeats:"10%",
description:"A platform for emerging musicians, poets, and performers to showcase their talents before a supportive audience. The open stage encourages creativity, collaboration, and discovery of new indie voices in music, poetry, and storytelling."
},

{
id:515,
genre:"Open Mic",
name:"Standup & Music Jam Night",
date:"10 Aug 2026",
time:"7:30 PM",
location:"Guwahati",
performer:"Jam Creators Hub",
venue:"Guwahati Art Lounge",
ticketPrice:450,
gst:18,
totalSeats:220,
seatsBooked:80,
availableSeats:140,
discount3Seats:"5%",
discount5PlusSeats:"10%",
description:"A lively evening blending stand-up comedy, live music jams, and spontaneous performances. Artists and audience members come together to share laughs, enjoy music collaborations, and celebrate creative expression in a relaxed social setting."
},

{
id:516,
genre:"Sports",
name:"Pro Kabaddi Fan Fest",
date:"14 May 2026",
time:"6:00 PM",
location:"Chennai",
organizer:"National Kabaddi Association",
venue:"Jawaharlal Nehru Indoor Stadium",
ticketPrice:1000,
gst:18,
totalSeats:500,
seatsBooked:260,
availableSeats:240,
discount3Seats:"8%",
discount5PlusSeats:"15%",
description:"Kabaddi fans can experience thrilling matches, meet star players, and participate in interactive games during this exciting fan festival. The event celebrates India's beloved sport with live entertainment, merchandise stalls, and engaging fan activities."
},

{
id:517,
genre:"Performance",
name:"Kathak Classical Evening",
date:"05 May 2026",
time:"6:00 PM",
location:"Lucknow",
performer:"Kathak Dance Ensemble",
venue:"Bhatkhande Music Institute Auditorium",
ticketPrice:900,
gst:18,
totalSeats:300,
seatsBooked:140,
availableSeats:160,
discount3Seats:"7%",
discount5PlusSeats:"12%",
description:"A graceful evening of traditional Kathak dance performed by renowned artists. The performance highlights classical storytelling, intricate footwork, and expressive movements rooted in India's rich cultural heritage."
},

{
id:518,
genre:"Fest & Fairs",
name:"Kolkata Heritage Utsav",
date:"12 Jun 2026",
time:"3:30 PM",
location:"Kolkata",
organizer:"Bengal Cultural Committee",
venue:"Eco Park Amphitheatre",
ticketPrice:700,
gst:18,
totalSeats:450,
seatsBooked:210,
availableSeats:240,
discount3Seats:"6%",
discount5PlusSeats:"12%",
description:"Celebrate Bengal's heritage through folk music, traditional crafts, street food, and cultural performances. The festival offers visitors a vibrant glimpse into Kolkata's artistic traditions and lively community celebrations."
},

{
id:519,
genre:"Sports",
name:"Midnight Marathon Run",
date:"22 May 2026",
time:"11:30 PM",
location:"Kolkata",
organizer:"City Runners Club",
venue:"Salt Lake Stadium Track",
ticketPrice:600,
gst:18,
totalSeats:800,
seatsBooked:500,
availableSeats:300,
discount3Seats:"6%",
discount5PlusSeats:"12%",
description:"Join hundreds of runners in an energetic midnight marathon through illuminated city routes. The event promotes fitness, community spirit, and endurance while offering an exciting late-night running experience."
},

{
id:520,
genre:"NightLife",
name:"Nucleya EDM Carnival",
date:"30 Apr 2026",
time:"10:30 PM",
location:"Goa",
performer:"Nucleya",
venue:"Club Cubana Arena",
ticketPrice:3000,
gst:18,
totalSeats:700,
seatsBooked:520,
availableSeats:180,
discount3Seats:"10%",
discount5PlusSeats:"18%",
description:"An electrifying EDM carnival featuring powerful beats by Nucleya and spectacular stage production. The night promises high-energy music, vibrant lights, and an unforgettable party atmosphere for electronic music lovers."
},

{
id:521,
genre:"Exhibition",
name:"Photography World Expo",
date:"25 Jun 2026",
time:"10:30 AM",
location:"Noida",
organizer:"Lenscape Community",
venue:"India Expo Mart",
ticketPrice:750,
gst:18,
totalSeats:350,
seatsBooked:140,
availableSeats:210,
discount3Seats:"7%",
discount5PlusSeats:"12%",
description:"A visual celebration of photography showcasing breathtaking images, creative workshops, and advanced camera technology. Enthusiasts can interact with professionals and explore innovative techniques in modern photography."
},

{
id:522,
genre:"Open Mic",
name:"Poetry & Stories Night",
date:"02 Aug 2026",
time:"6:30 PM",
location:"Chandigarh",
performer:"Spoken Word Collective",
venue:"Chandigarh Arts Theatre",
ticketPrice:350,
gst:18,
totalSeats:200,
seatsBooked:70,
availableSeats:130,
discount3Seats:"5%",
discount5PlusSeats:"10%",
description:"An intimate evening where poets and storytellers share heartfelt pieces and personal narratives. The event encourages expressive creativity, emotional storytelling, and meaningful conversations among literature lovers."
},

{
id:523,
genre:"Performance",
name:"Rajasthani Folk Cult Night",
date:"09 May 2026",
time:"7:30 PM",
location:"Jaipur",
performer:"Rajasthani Folk Artists",
venue:"Jawahar Kala Kendra",
ticketPrice:800,
gst:18,
totalSeats:300,
seatsBooked:150,
availableSeats:150,
discount3Seats:"7%",
discount5PlusSeats:"12%",
description:"A vibrant showcase of traditional Rajasthani music and dance featuring colorful costumes, energetic performances, and cultural storytelling. Visitors experience the lively spirit and heritage of Rajasthan through authentic folk art."
},

{
id:524,
genre:"Expos",
name:"Real Estate Mega Expo",
date:"20 Jul 2026",
time:"11:00 AM",
location:"Indore",
organizer:"National Realty Council",
venue:"Indore Convention Centre",
ticketPrice:500,
gst:18,
totalSeats:400,
seatsBooked:160,
availableSeats:240,
discount3Seats:"5%",
discount5PlusSeats:"10%",
description:"A large real estate expo connecting property developers, investors, and homebuyers. Attendees can explore new housing projects, investment opportunities, and expert advice on property trends and financing."
},

{
id:525,
genre:"Comedy",
name:"Samay Raina Special",
date:"20 Apr 2026",
time:"7:30 PM",
location:"Mumbai",
performer:"Samay Raina",
venue:"St. Andrew's Auditorium",
ticketPrice:1700,
gst:18,
totalSeats:400,
seatsBooked:280,
availableSeats:120,
discount3Seats:"8%",
discount5PlusSeats:"15%",
description:"Enjoy an evening of spontaneous humor and witty observations with Samay Raina. Known for his engaging storytelling and relatable jokes, the show promises nonstop laughter and energetic crowd interaction."
},

{
id:526,
genre:"Music",
name:"Shreya Melody Tour",
date:"18 Apr 2026",
time:"7:00 PM",
location:"Bengaluru",
performer:"Shreya Ghoshal",
venue:"Bangalore Palace Grounds",
ticketPrice:3500,
gst:18,
totalSeats:800,
seatsBooked:560,
availableSeats:240,
discount3Seats:"10%",
discount5PlusSeats:"20%",
description:"A melodious evening with Shreya Ghoshal performing her most loved songs across Bollywood and regional music. The concert blends beautiful vocals, orchestral arrangements, and a magical live performance experience."
},

{
id:527,
genre:"Music",
name:"Sonu Nigam Live in Concert",
date:"25 Apr 2026",
time:"7:30 PM",
location:"Delhi",
performer:"Sonu Nigam",
venue:"Indira Gandhi Arena",
ticketPrice:3800,
gst:18,
totalSeats:900,
seatsBooked:640,
availableSeats:260,
discount3Seats:"10%",
discount5PlusSeats:"20%",
description:"Experience the timeless voice of Sonu Nigam in a grand live concert featuring Bollywood classics and soulful melodies. Fans can enjoy powerful performances accompanied by a full live orchestra."
},

{
id:528,
genre:"Conference",
name:"Startup India Summit",
date:"05 Jul 2026",
time:"9:30 AM",
location:"Bengaluru",
organizer:"Startup India Mission",
venue:"Bangalore International Convention Centre",
ticketPrice:2200,
gst:18,
totalSeats:500,
seatsBooked:210,
availableSeats:290,
discount3Seats:"10%",
discount5PlusSeats:"18%",
description:"A dynamic summit connecting entrepreneurs, investors, and startup founders to share ideas and innovation strategies. The event features keynote talks, networking sessions, and opportunities to pitch groundbreaking business ideas."
},

{
id:529,
genre:"NightLife",
name:"Sunidhi Chauhan Beats",
date:"26 Apr 2026",
time:"9:30 PM",
location:"Goa",
performer:"Sunidhi Chauhan",
venue:"Tito's Arena",
ticketPrice:3200,
gst:18,
totalSeats:650,
seatsBooked:420,
availableSeats:230,
discount3Seats:"10%",
discount5PlusSeats:"18%",
description:"A high-energy live music night featuring Sunidhi Chauhan's electrifying stage presence and powerful vocals. The concert combines Bollywood hits, dance music, and an unforgettable nightlife party experience."
},

{
id:530,
genre:"Comedy",
name:"Zakir Khan – Sakht Launda",
date:"15 Apr 2026",
time:"6:30 PM",
location:"Delhi",
performer:"Zakir Khan",
venue:"Talkatora Stadium Auditorium",
ticketPrice:2000,
gst:18,
totalSeats:500,
seatsBooked:350,
availableSeats:150,
discount3Seats:"8%",
discount5PlusSeats:"15%",
description:"A laugh-filled stand-up comedy show by Zakir Khan featuring his signature storytelling style and relatable humor. Fans will enjoy witty observations, heartfelt moments, and the iconic 'Sakht Launda' charm."
}

]

export default eventsData;